### ISSUE TITLE
Annotations showing on multiple pages

### ISSUE THREAD

**Issue by oxhey** [aron/annotator.offline.js#3]
I'm adding annotations to reveal.js presentations . The code im using is based on the example as well as the two other issues posted. 

The problem is that an annotation from one presentation still loads on another.

 jQuery('Lecture 1').text(); is changed to  jQuery('Lecture 2').text(); in the other reveal presententaion.

```
    <script>
    var content = jQuery(".reveal").annotator();
    content.annotator('addPlugin', 'Offline', {
      setAnnotationData: function (ann) {
    if (!ann.pageName) {
      ann.pageName = jQuery('Lecture 1').text(); // Use the page title
    }
  },
  shouldLoadAnnotation: function (ann) {
    return ann.pageName === jQuery('Lecture 1').text();
  },
      online:  function () {
        jQuery("#status").text("Online");
      },
      offline: function () {
        jQuery("#status").text("Offline");
      }
    });
    var annotator = content.data('annotator');

    jQuery("#clear-storage").click(function () {
      if (annotator) {
        annotator.plugins.Offline.store.clear()
      }
    });
    </script>
```

**Comment by aron** [comment]
I'm not sure what you want `jQuery` to be doing here. You need to pass it a CSS selector not a piece of text. If you want to get the title of the page you can use `jQuery('title').text()` otherwise you can just use the string "Lecture 1" as you have it without the jQuery part.

Please feel free to re-open this if you're still having issues.
